objc: true
clean: true
sdk: macosx

module: HockeySDK
module_version: 5.1.1
author: Microsoft Corp
author_url: https://www.microsoft.com

readme: ../../README.md
documentation: ../Guides/*.md
custom_categories:
  - name: Guides
    children:
    - Installation & Setup
    - Installation Mac App
    - Migration
  - name: How To
    children:
    - App Versioning
    - Upload Symbols
  - name: Troubleshooting
    children:
    - Crash Reporting Not Working
  - name: Release Notes
    children:
    - Changelog

umbrella_header: ../../Classes/HockeySDK.h
framework_root: ../../Classes

root_url: https://support.hockeyapp.net/kb/api
github_url: https://github.com/bitstadium/HockeySDK-Mac/
github_file_prefix: "https://github.com/bitstadium/HockeySDK-Mac/"

skip_undocumented: true

output: Generated/
